# Generated by Django 3.2.9 on 2021-11-03 00:03

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pochette',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=45, unique=True, verbose_name='titre')),
                ('image', django_resized.forms.ResizedImageField(crop=['top', 'left'], force_format=None, keep_meta=True, quality=75, size=[400, 240], upload_to='albums_photo/')),
                ('image_for_detail_page', django_resized.forms.ResizedImageField(blank=True, crop=None, editable=False, force_format=None, keep_meta=True, quality=75, size=[550, 350], upload_to='albums_photo_details/')),
                ('pub_date', models.DateField(auto_now_add=True)),
                ('slug', autoslug.fields.AutoSlugField(blank=True, editable=True, populate_from='title', unique_with=['title', 'pub_date__month'])),
                ('is_public', models.BooleanField(default=False, verbose_name='public')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pochettes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
