# Generated by Django 3.2.9 on 2021-11-02 20:47

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_prochette', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pochette',
            name='image_for_detail_page',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, editable=False, force_format=None, keep_meta=True, quality=75, size=[550, 350], upload_to='albums_photo_details/'),
        ),
    ]
