# Generated by Django 3.2.9 on 2021-11-03 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_prochette', '0006_alter_pochette_image_for_detail_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pochette',
            name='image_for_detail_page',
            field=models.ImageField(blank=True, editable=False, upload_to='albums_photo_details/'),
        ),
    ]
